databases:
  - name: mamatech_website
    databaseName: mamatech_website
    user: mamatech_website
    plan: free

services:
  - type: web
    plan: free
    name: mamatech_website
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mamatech_website
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: MAILTRAP_API_KEY
        value: "your-mailtrap-api-key"
      - key: RAILS_ENV
        value: "production"
      - key: SECRET_KEY_BASE
        value: "your-secret-key-base"
